package entity;
// Generated Sep 2, 2015 2:15:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Computer generated by hbm2java
 */
public class Computer  implements java.io.Serializable {


     private Integer id;
     private String cpu;
     private String video;
     private String тест;
     private Set persons = new HashSet(0);

    public Computer() {
    }

    public Computer(String cpu, String video, String тест, Set persons) {
       this.cpu = cpu;
       this.video = video;
       this.тест = тест;
       this.persons = persons;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCpu() {
        return this.cpu;
    }
    
    public void setCpu(String cpu) {
        this.cpu = cpu;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }
    public String getТест() {
        return this.тест;
    }
    
    public void setТест(String тест) {
        this.тест = тест;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }




}


